### ISSUE TITLE
IC-3 query

### ISSUE THREAD

**Issue by jennet** [Swirrl/pmd-rdf-validations#7]
Reported on rdf-validator here https://github.com/Swirrl/rdf-validator/issues/17

**Comment by Robsteranium** [comment]
I've posted a [suggested correction on the upstream issue](https://github.com/Swirrl/rdf-validator/issues/17#issuecomment-972958854).

**Comment by Robsteranium** [comment]
Resolved in 9400e98440f969d1f2af4204f25a4a3406fd7363.
